### ISSUE TITLE
Kreta Ayer Beta In-App Preloading Page Content

### ISSUE THREAD

**Issue by Yipei-Operation** [toeverything/AFFiNE-Community#13]

**Comment by ShortCipher5** [comment]
Current revision: https://app.affine.pro/public-workspace/uvhXnx4KIY2ODua3s1DGT/KimcIHLwf7

**Comment by ShortCipher5** [comment]
The content had been revised based on feedback (@joebeijing):

1. Pinboard introduction removed - the feature will be significantly changed
2. Page mode introduction focusses first on "write"
3. Similarly Edgeless is first introduced through "whiteboard"
4. General introduction added to start
5. Added plan section (Write, Draw, Plan) - with a focus on Database

**Comment by houjoe0829** [comment]
So is there a public link that I can preview? @ShortCipher5
