### ISSUE TITLE
AFFiNE Documents and Guides

### ISSUE THREAD

**Issue by xell** [toeverything/AFFiNE-Community#17]
Pre-loading is too limited and we need to cover more operations and usecases

## Changes

- A suitable entry point needs to be considered
    - On workspace selection screen - add an area to access the AFFiNE public doc centre?
- This will be a public workspace hosted on AFFiNE Cloud
    1. Preparations to be made
      1. Creating layout and draft content
      2. Preparing videos and other instructions
    2. Whether this is officially released depends on development
      1. Can videos be embedded
      2. Is AFFiNE Cloud completed early enough to allow time for this workspace to be created and setup

## Reasoning

Users need more user guides and quick tips to make the most of AFFiNE. Preload content only covers the basics, but we can create short intro guides for various different features and the different actions that can be achieved - e.g. Guiding users through the import process.

## Related

- [ ] https://github.com/toeverything/AFFiNE/issues/2172

ref [internal doc](https://toeverything.feishu.cn/wiki/GGqRwBrUXis2cxkqbXwc5m47nXd)

**Comment by Yipei-Operation** [comment]
Update: 
0.8.0 will have a new pre-loading content with {New to AFFiNE}
and hope 0.9.0 we can have a public workspace for help center

**Comment by xell** [comment]
Closed as this will be replaced by newer issues such as https://github.com/toeverything/AFFiNE/issues/3679 .
