### ISSUE TITLE
Better to give a choice for users to decide where to install AFFiNE

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE-Community#19]
![Image](https://user-images.githubusercontent.com/121489905/240145009-d25c772a-3697-4512-9509-0e6cb984c442.png)

https://discord.com/channels/959027316334407691/959033875856756756/1108799245722595438

**Comment by xell** [comment]
It need further research about the installation convention in Windows 11/10 @joebeijing

**Comment by xell** [comment]
Issue has been planned https://github.com/toeverything/AFFiNE/issues/2792

**Comment by ShortCipher5** [comment]
Followed up with user.
