### ISSUE TITLE
Need a scrollbar to quickly position where I am in the whole doc

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE-Community#20]
![Image](https://user-images.githubusercontent.com/121489905/240146658-5efda459-5f93-4808-89ed-e5b02e931ffd.png)

https://discord.com/channels/959027316334407691/959033875856756756/1108849207730774147

**Comment by xell** [comment]
I've talked to Xiao Peng and Qi Shaoxuan about this. We need further research about the design and implementation both in macOS and Windows. Perhaps this will be assigned to Yang Jinfei.

**Comment by xell** [comment]
Issue has been planned https://github.com/toeverything/AFFiNE/issues/2793

**Comment by ShortCipher5** [comment]
Followed up with user.
