### ISSUE TITLE
TOC Generator plugin is needed to make navigation quicker and see the structure of your page easily

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE-Community#21]
![Image](https://user-images.githubusercontent.com/121489905/240146733-a42639c2-3c35-40b6-bbdc-856db63b37c3.png)

https://discord.com/channels/959027316334407691/959033875856756756/1108849207730774147

**Comment by houjoe0829** [comment]
![Image](https://github.com/toeverything/AFFiNE-Community/assets/22443345/7dba28f3-904a-4e35-82d6-860579664200)

**Comment by xell** [comment]
might be in next milestone. already mentioned in https://github.com/toeverything/AFFiNE/issues/1557

**Comment by ShortCipher5** [comment]
Followed up with user.
