### ISSUE TITLE
The corners of Affine are not rounded on Windows

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE-Community#22]
![Image](https://user-images.githubusercontent.com/121489905/240146856-f08b6526-3e69-4812-8970-32e2050facc4.png)

Ohh makes sense, yeah that's on Windows. Also corners of Affine are not rounded on Windows. I'm using Win10 so idk if it's working as intended on Win11 tho.

**Comment by xell** [comment]
We're not able to find out the cause of this issue yet.

**Comment by ShortCipher5** [comment]
Followed up with user.
