### ISSUE TITLE
 the shortcut for a quick search is Ctrl + K. However, when I want to find a page, I don't put both of my hands on the keyboard and so the problem is that "K" is too far away

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE-Community#23]
https://discord.com/channels/959027316334407691/1109131374138490930/1109131374138490930

![Image](https://user-images.githubusercontent.com/121489905/240218145-88d57eae-3bec-4ef5-a9ea-1b13c7fd7586.jpeg)

**Comment by xell** [comment]
it's by design. please reply to the user politely.  @ShortCipher5

**Comment by ShortCipher5** [comment]
Followed up with the user.
