### ISSUE TITLE
Ctrl + F combination that opens up a find box

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE-Community#24]
![Image](https://user-images.githubusercontent.com/121489905/240218455-22f4dbe0-d4de-4636-ba9f-c508db1a9999.jpeg)

https://discord.com/channels/959027316334407691/1109131374138490930/1109131374138490930

**Comment by xell** [comment]
It will be planned in the future roadmap.

**Comment by ShortCipher5** [comment]
Followed up with user.
