### ISSUE TITLE
Can we get a self-hosted docker image with beta tag?

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE-Community#25]

**Comment by ShortCipher5** [comment]
1) Self-host (server side)
2) Client can connect to self-host sever?

**Comment by xell** [comment]
ref to  https://github.com/toeverything/OctoBase/issues/457 and https://github.com/toeverything/AFFiNE/issues/2646 , which will be raised up in the milestone plan.

**Comment by EYHN** [comment]
Tracked in https://github.com/toeverything/AFFiNE/issues/5069
