### ISSUE TITLE
The ability to reference blocks from other pages

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE-Community#26]
Logseq is a great example, but with how easy it is to edit blocks in Affine, I think it could be implemented really nice and clean.

![Image](https://user-images.githubusercontent.com/121489905/240219276-111f10b1-3324-4a89-9aba-a6519b090d5f.jpeg)

https://discord.com/channels/959027316334407691/1109131374138490930/1109131374138490930

**Comment by xell** [comment]
It's planned in https://github.com/toeverything/blocksuite/issues/2268 but due to the workload, Doodlewind had removed it from the 0.7 milestone and set up no deadline for it.

**Comment by ShortCipher5** [comment]
Followed up with user.
