### ISSUE TITLE
Properties, like in Notion, would be amazing. help to add context to your pages and assist a lot with organizing your workspace in general.

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE-Community#27]
![Image](https://user-images.githubusercontent.com/121489905/240221126-ad7f9dd2-f560-459a-8c67-768e2a112266.jpeg)

https://discord.com/channels/959027316334407691/1109131374138490930/1109131374138490930

**Comment by xell** [comment]
It will be partially realized by tags in page https://github.com/toeverything/AFFiNE/issues/2165 .

**Comment by ShortCipher5** [comment]
Followed up with user.
