### ISSUE TITLE
Calendar View

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE-Community#28]
![Image](https://user-images.githubusercontent.com/4605025/240471356-82dd129d-b5c1-4332-9773-da088a3b066d.png)

**Comment by xell** [comment]
@ShortCipher5 please ask the user more about the details of this feature request. And the screenshot might be irrelevant.

**Comment by xell** [comment]
It has been planned in https://github.com/toeverything/AFFiNE/issues/2152

**Comment by ShortCipher5** [comment]
Followed up with user.
