### ISSUE TITLE
Relation graph

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE-Community#30]
![Image](https://user-images.githubusercontent.com/4605025/240471356-82dd129d-b5c1-4332-9773-da088a3b066d.png)

![Image](https://user-images.githubusercontent.com/4605025/240472848-ae18b00f-60fd-4fcf-924f-2799e4730a17.png)

**Comment by xell** [comment]
it will not be planned in the short future.

**Comment by ShortCipher5** [comment]
User has been notified.
