### ISSUE TITLE
Use native window UI (Windows)

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE-Community#33]
![Image](https://user-images.githubusercontent.com/4605025/240494624-6998ae14-2f74-4c3a-9829-b16321b43ba6.png)

https://discord.com/channels/959027316334407691/1108967686563704882/1110605150541840474

**Comment by xell** [comment]
On one hand, regarding the overall design principle and workload of the dev team, most of the Windows compatibility issues will not be covered. On the other hand, the "far-top-right-corner-close-button" issue will be handled specially because it does violate the daily experience of Windows users.
