### ISSUE TITLE
use mouse wheel click grab to navigate around a canvas, is there a way to enable navigation with mouse wheel instead of spacebar

### ISSUE THREAD

**Issue by Yipei-Operation** [toeverything/AFFiNE-Community#34]
![Image](https://github.com/toeverything/AFFiNE-Community/assets/79373028/47968f06-0cd1-4cd8-8c9f-faa9f42efe65)

**Comment by houjoe0829** [comment]
Already created an issue to follow up https://github.com/toeverything/blocksuite/issues/3033
Please take a look @xell

**Comment by xell** [comment]
It's been planned in 0.7.

**Comment by ShortCipher5** [comment]
Followed up with user.
