### ISSUE TITLE
Nested folders that could be accessed from the sidebar, like in obsidian

### ISSUE THREAD

**Issue by Yanxi0202** [toeverything/AFFiNE-Community#38]
![Image](https://user-images.githubusercontent.com/134897361/246352324-3bed2777-47bf-44e1-8096-2ea99a24e8ae.png)

**Comment by xell** [comment]
In AFFiNE, we used network topology to organize docs, i.e. pages and edgeless whiteboards. And we do have a page tree structure to display in the Favourites section. We will prepare a document for this part.
