### ISSUE TITLE
Edgeless eraser tool

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE-Community#40]
![Image](https://user-images.githubusercontent.com/4605025/247006292-6ba03ae1-1274-4441-8801-12e609220471.png)

![Image](https://user-images.githubusercontent.com/4605025/247006067-50f97688-2b23-4b5c-bc74-c65c60ee0cab.png)

![Image](https://user-images.githubusercontent.com/4605025/247006155-921a06d9-792e-4852-bee1-dcf709aeb6bc.png)

Source: https://discord.com/channels/959027316334407691/1021644403498033242/1120351281094082581

**Comment by xell** [comment]
In this 0.7 version we will probably offer a **shape-wise** eraser for remove a specific shape as it is, but a pixel-wise eraser like the user suggested will be considered in the future.
