### ISSUE TITLE
Kanban

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE-Community#44]
Adding KanBan (Dataabase view)

**Comment by ShortCipher5** [comment]
Newest First

**Discord Mentions**

https://discord.com/channels/959027316334407691/959033875856756756/1126872097134743632

https://discord.com/channels/959027316334407691/959033875856756756/1122765898583900190

https://discord.com/channels/959027316334407691/959033875856756756/1104945961425444986

https://discord.com/channels/959027316334407691/1087974154021650432/1100348488497233931

https://discord.com/channels/959027316334407691/959033875856756756/1088871108431851520

https://discord.com/channels/959027316334407691/959033875856756756/1061008480447774861

https://discord.com/channels/959027316334407691/959033875856756756/1009594379243114596


**Community Mentions**

https://community.affine.pro/c/questions-answers/kanban-like-boards

https://community.affine.pro/c/questions-answers/the-three-column-view-with-groupby#comment_wrapper_17959105

**Reddit**

https://www.reddit.com/r/Affine/comments/14zri22/how_to_get_kanban_board/

**Comment by xell** [comment]
We've already consider this as an important function https://github.com/toeverything/blocksuite/issues/2401 , but it depends on the fundamental construction of the database so there's no schedule now.
