### ISSUE TITLE
To-do mark completed strikethrough

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE-Community#67]
Users think the style of a completed to-do is too similar to an unfinished one.

Users would like to see a bigger visual difference - such as strikethrough text.

Source: https://discord.com/channels/959027316334407691/959033875856756756/1128640934473650246

**Comment by ShortCipher5** [comment]
Example

![Image](https://github.com/toeverything/AFFiNE-Community/assets/4605025/6b1508e3-bbeb-45e0-9a42-0760f104910d)

**Comment by xell** [comment]
We've put this request into our internal plan and the issue will be added till the time is right.
