### ISSUE TITLE
Block layouts - side-by-side placement

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE-Community#68]
Add the ability to place blocks in more advanced views.

For example a 2 column layout to be able to place text on the left and an image on the right.

Source: https://discord.com/channels/959027316334407691/959033875856756756/1126222834608373790

**Comment by xell** [comment]
We agree this is a common and nice-to-have function, but due to the workload of 0.8 milestone, it will be considered at least next stage.
