### ISSUE TITLE
request for similar to quote twitter feature

### ISSUE THREAD

**Issue by Yanxi0202** [toeverything/AFFiNE-Community#73]
![Image](https://user-images.githubusercontent.com/134897361/254791204-258173d3-c2ea-4679-bbd4-b191cfaeb765.png)
more details please refer to: https://discord.com/channels/959027316334407691/959033875856756756/1131368871450910781

**Comment by xell** [comment]
perhaps https://github.com/toeverything/blocksuite/issues/2268
