### ISSUE TITLE
Feature request -  customize the colors of links, tags, and headers

### ISSUE THREAD

**Issue by PaxtonXuan** [toeverything/AFFiNE-Community#74]
Discord Link: https://discord.com/channels/959027316334407691/959033875856756756/1131273602793226463

**Comment by xell** [comment]
This request seems involving many details. It needs to be clarified as:

1. Is it something like text highlight or text color function in Notion?
2. Is it related with color themes, by which every elements of the doc will be colorized?
3. Or is it like the "Accent Color" function in the appearance settings of macOS?
4. As for the tags in database and page, customizing colors is already available.

Please discuss with the user to let us know more about it.

**Comment by houjoe0829** [comment]
I really think that this is the same as Bear Note's Theme feature, but let's wait for further feedback from users first.

<img width="570" alt="CleanShot 2023-07-21 at 16 34 54@2x" src="https://github.com/toeverything/AFFiNE-Community/assets/22443345/89835720-a399-4ece-8a90-15b4db943593">
