### ISSUE TITLE
no way to quickly turn a series of text lines into new subpages

### ISSUE THREAD

**Issue by Yanxi0202** [toeverything/AFFiNE-Community#76]
![Image](https://user-images.githubusercontent.com/134897361/254794537-68bdf3e3-078b-48ec-8144-316e60851f0c.jpg)

**Comment by houjoe0829** [comment]
Providing user feedback requires traceability, so be sure to include a message link. @Yanxi0202

**Comment by houjoe0829** [comment]
However, this requirement is definitely worth supporting in the future and has been added to the [backlog](https://toeverything.feishu.cn/record/1sfvuYmGuMrrpo5lE62B3dbUv).
