### ISSUE TITLE
Copy as PNG - UI text wrapping issue

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE-Community#79]
See image "copy original link".

![Image](https://user-images.githubusercontent.com/4605025/255536221-e6086520-8961-477b-a55b-4b7320ceea78.png)

Source: https://community.affine.pro/c/bug-reports/app-perf-text-too-long

**Comment by xell** [comment]
As for apparent bugs, please directly create new issue in the proper repo.
