### ISSUE TITLE
Cannot create non-English sub doc

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE-Community#80]
When creating a sub-doc with `@` the input does not allow for input outside of the general A-Z.

This issue applies to Chinese characters and potentially accented characters.

![Image](https://user-images.githubusercontent.com/4605025/255537038-390e1440-7656-481e-8638-4191ae028ca6.png)

Source: https://community.affine.pro/c/bug-reports/create-26a7ec

**Comment by xell** [comment]
It's regression bug only in canary. It's ok in stable 0.7. Moreover, as for apparent bugs, please directly create new issue in the proper repo.

**Comment by ShortCipher5** [comment]
Closing as potentially resolved (not present in latest stable).
